/**
 * bpmn.js 中文翻译
 */
export default {
    'Activate the global connect tool': '激活全局连接工具',
    'Activate the hand tool': '激活手动工具',
    'Activate the lasso tool': '激活套索工具',
    'Activate the create/remove space tool': '激活创建/删除空间工具',
    'Add Lane above': '在上方添加泳道',
    'Add Lane below': '在下方添加泳道',
    'Append EndEvent': '追加结束事件',
    'Append Gateway': '追加网关',
    'Append Task': '追加任务',
    'Append Intermediate/Boundary Event': '追加中间/边界事件',
    'Business Rule Task': '业务规则任务',
    'Call Activity': '调用活动',
    'Change type': '更改类型',
    'Collapsed Pool': '折叠池',
    'Compensation Boundary Event': '补偿边界事件',
    'Complex Gateway': '复杂网关',
    'Conditional Boundary Event': '条件边界事件',
    'Conditional Boundary Event (non-interrupting)': '条件边界事件（非中断）',
    'Conditional Intermediate Catch Event': '条件中间捕获事件',
    'Conditional Start Event': '条件开始事件',
    'Conditional Start Event (non-interrupting)': '条件开始事件（非中断）',
    'Connect using Association': '使用关联连接',
    'Connect using DataInputAssociation': '使用数据输入关联连接',
    'Connect using Sequence/MessageFlow or Association': '使用顺序/消息流或关联连接',
    'Create DataObjectReference': '创建数据对象引用',
    'Create DataStoreReference': '创建数据存储引用',
    'Create EndEvent': '创建结束事件',
    'Create Gateway': '创建网关',
    'Create Group': '创建组',
    'Create Intermediate/Boundary Event': '创建中间/边界事件',
    'Create Pool/Participant': '创建池/参与者',
    'Create StartEvent': '创建开始事件',
    'Create Task': '创建任务',
    'Create expanded SubProcess': '创建展开的子流程',
    'Divide into three Lanes': '分成三条泳道',
    'Divide into two Lanes': '分成两条泳道',
    'Empty Pool': '空池',
    'End Event': '结束事件',
    'Error Boundary Event': '错误边界事件',
    'Error End Event': '错误结束事件',
    'Error Start Event': '错误开始事件',
    'Escalation Boundary Event': '升级边界事件',
    'Escalation Boundary Event (non-interrupting)': '升级边界事件（非中断）',
    'Escalation End Event': '升级结束事件',
    'Escalation Intermediate Throw Event': '升级中间抛出事件',
    'Escalation Start Event': '升级开始事件',
    'Event Sub Process': '事件子流程',
    'Event-based Gateway': '事件网关',
    'Exclusive Gateway': '排他网关',
    'Expanded Pool': '展开池',
    'Inclusive Gateway': '包容网关',
    'Intermediate Throw Event': '中间抛出事件',
    'Link Intermediate Catch Event': '链接中间捕获事件',
    'Link Intermediate Throw Event': '链接中间抛出事件',
    'Loop': '循环',
    'Manual Task': '手动任务',
    'Message Boundary Event': '消息边界事件',
    'Message Boundary Event (non-interrupting)': '消息边界事件（非中断）',
    'Message End Event': '消息结束事件',
    'Message Intermediate Catch Event': '消息中间捕获事件',
    'Message Intermediate Throw Event': '消息中间抛出事件',
    'Message Start Event': '消息开始事件',
    'Message Start Event (non-interrupting)': '消息开始事件（非中断）',
    'Multi-instance': '多实例',
    'Parallel Gateway': '并行网关',
    'Parallel Multi-instance': '并行多实例',
    'Receive Task': '接收任务',
    'Remove': '删除',
    'Script Task': '脚本任务',
    'Send Task': '发送任务',
    'Sequential Multi-instance': '顺序多实例',
    'Service Task': '服务任务',
    'Signal Boundary Event': '信号边界事件',
    'Signal Boundary Event (non-interrupting)': '信号边界事件（非中断）',
    'Signal End Event': '信号结束事件',
    'Signal Intermediate Catch Event': '信号中间捕获事件',
    'Signal Intermediate Throw Event': '信号中间抛出事件',
    'Signal Start Event': '信号开始事件',
    'Signal Start Event (non-interrupting)': '信号开始事件（非中断）',
    'Start Event': '开始事件',
    'Sub Process': '子流程',
    'Sub Process (collapsed)': '子流程（折叠）',
    'Sub Process (expanded)': '子流程（展开）',
    'Task': '任务',
    'Terminate End Event': '终止结束事件',
    'Timer Boundary Event': '定时边界事件',
    'Timer Boundary Event (non-interrupting)': '定时边界事件（非中断）',
    'Timer Intermediate Catch Event': '定时中间捕获事件',
    'Timer Start Event': '定时开始事件',
    'Timer Start Event (non-interrupting)': '定时开始事件（非中断）',
    'Transaction': '事务',
    'User Task': '用户任务',
    'already rendered {element}': '已渲染 {element}',
    'diagram not part of bpmn:Definitions': '图表不是 bpmn:Definitions 的一部分',
    'element {element} referenced by {referenced}#{property} not yet drawn': '元素 {element} 被 {referenced}#{property} 引用但尚未绘制',
    'failed to import {element}': '导入 {element} 失败',
    'flow elements must be children of pools/participants': '流元素必须是池/参与者的子元素',
    'more than {count} child lanes': '超过 {count} 条子泳道',
    'no diagram to display': '没有可显示的图表',
    'no parent for {element} in {parent}': '{parent} 中没有 {element} 的父元素',
    'no process or collaboration to display': '没有可显示的流程或协作',
    'no shape type specified': '未指定形状类型',
    'out of bounds release': '超出范围释放',
    'Append {type}': '追加 {type}',
    'Add {type}': '添加 {type}',
    'Create {type}': '创建 {type}',
    'Connect to {type}': '连接到 {type}',
    'Replace with {type}': '替换为 {type}',
    'Change Element': '更改元素',
    'Properties Panel': '属性面板',
    'General': '常规',
    'Id': '标识',
    'Name': '名称',
    'Documentation': '文档',
    'Element Documentation': '元素文档',
    'Process Id': '流程标识',
    'Process Name': '流程名称',
    'Executable': '可执行',
    'Assignee': '办理人',
    'Candidate Users': '候选用户',
    'Candidate Groups': '候选组',
    'Due Date': '到期日期',
    'Follow Up Date': '跟进日期',
    'Priority': '优先级',
    'Collection': '集合',
    'Element Variable': '元素变量'
}
