-- 高考志愿录取分数库表结构
-- 说明：candidate_province_code/name 表示考生省份，用于隔离不同省份录取数据。

CREATE TABLE IF NOT EXISTS `edu_college_admission_score` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `admission_year` smallint NOT NULL COMMENT '录取年份',
  `candidate_province_code` varchar(12) NOT NULL COMMENT '考生省份编码，河南为410000',
  `candidate_province_name` varchar(32) NOT NULL COMMENT '考生省份名称',
  `college_name` varchar(128) NOT NULL COMMENT '院校名称',
  `college_code` varchar(32) DEFAULT NULL COMMENT '招生院校代码，保留前导零',
  `subject_category` varchar(32) NOT NULL COMMENT '科类，如物理类、历史类',
  `batch_name` varchar(32) NOT NULL COMMENT '批次',
  `major_group_code` varchar(32) DEFAULT NULL COMMENT '专业组',
  `selection_requirement` varchar(128) DEFAULT NULL COMMENT '选科要求',
  `admission_type` varchar(64) DEFAULT NULL COMMENT '录取类型/计划性质，源表缺失时为空',
  `admission_count` int unsigned DEFAULT NULL COMMENT '录取人数',
  `min_score` smallint unsigned NOT NULL COMMENT '最低分数',
  `min_rank` int unsigned DEFAULT NULL COMMENT '最低分位/最低位次',
  `batch_line_diff` smallint DEFAULT NULL COMMENT '批次线差',
  `college_province_name` varchar(32) DEFAULT NULL COMMENT '学校所在省份',
  `college_nature` varchar(32) DEFAULT NULL COMMENT '学校性质',
  `is_985` tinyint NOT NULL DEFAULT '0' COMMENT '是否985：0否，1是',
  `is_211` tinyint NOT NULL DEFAULT '0' COMMENT '是否211：0否，1是',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-未删除，1-已删除）',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_score_query` (`candidate_province_code`, `admission_year`, `subject_category`, `batch_name`, `min_score`, `min_rank`) USING BTREE,
  KEY `idx_college` (`candidate_province_code`, `admission_year`, `college_code`) USING BTREE,
  KEY `idx_group` (`candidate_province_code`, `admission_year`, `college_code`, `subject_category`, `batch_name`, `major_group_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='高考院校录取分数线表';

CREATE TABLE IF NOT EXISTS `edu_major_admission_score` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `admission_year` smallint NOT NULL COMMENT '录取年份',
  `candidate_province_code` varchar(12) NOT NULL COMMENT '考生省份编码，河南为410000',
  `candidate_province_name` varchar(32) NOT NULL COMMENT '考生省份名称',
  `college_name` varchar(128) NOT NULL COMMENT '院校名称',
  `college_code` varchar(32) DEFAULT NULL COMMENT '招生院校代码，保留前导零',
  `subject_category` varchar(32) NOT NULL COMMENT '科类，如物理类、历史类',
  `batch_name` varchar(32) NOT NULL COMMENT '批次',
  `selection_requirement` varchar(128) DEFAULT NULL COMMENT '选科要求',
  `major_name` varchar(128) NOT NULL COMMENT '专业名称',
  `major_code` varchar(32) DEFAULT NULL COMMENT '专业代码，保留前导零',
  `major_group_code` varchar(32) DEFAULT NULL COMMENT '所属专业组',
  `major_remark` varchar(500) DEFAULT NULL COMMENT '专业备注',
  `admission_type` varchar(64) DEFAULT NULL COMMENT '录取类型/计划性质，源表缺失时为空',
  `admission_count` int unsigned DEFAULT NULL COMMENT '录取人数',
  `min_score` smallint unsigned NOT NULL COMMENT '最低分数',
  `min_rank` int unsigned DEFAULT NULL COMMENT '最低位次',
  `college_province_name` varchar(32) DEFAULT NULL COMMENT '学校所在省份',
  `college_nature` varchar(32) DEFAULT NULL COMMENT '学校性质',
  `is_985` tinyint NOT NULL DEFAULT '0' COMMENT '是否985：0否，1是',
  `is_211` tinyint NOT NULL DEFAULT '0' COMMENT '是否211：0否，1是',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-未删除，1-已删除）',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_score_query` (`candidate_province_code`, `admission_year`, `subject_category`, `batch_name`, `min_score`, `min_rank`) USING BTREE,
  KEY `idx_college_group` (`candidate_province_code`, `admission_year`, `college_code`, `subject_category`, `batch_name`, `major_group_code`) USING BTREE,
  KEY `idx_major_name` (`major_name`) USING BTREE,
  KEY `idx_major_code` (`major_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='高考专业录取分数线表';
