-- 股票行业中英文映射枚举初始化
-- 枚举类型：stock_industry
-- 用途：股票列表页面行业字段中英文转换

-- 删除已存在的数据（如果需要重新初始化）
DELETE FROM sys_enum WHERE enum_type = 'stock_industry';

INSERT INTO sys_enum (enum_type, type_desc, enum_code, enum_value, description, sort, status, create_by, deleted) VALUES
('stock_industry', '股票行业', 'Advertising/Marketing Services', '广告/营销服务', '广告/营销服务', 1, 1, 'system', 0),
('stock_industry', '股票行业', 'Motor Vehicles', '汽车', '汽车行业', 2, 1, 'system', 0),
('stock_industry', '股票行业', 'Auto Parts: OEM', '汽车零部件:OEM', '汽车零部件OEM', 3, 1, 'system', 0),
('stock_industry', '股票行业', 'Medical Distributors', '医疗分销商', '医疗分销商', 4, 1, 'system', 0),
('stock_industry', '股票行业', 'Other Consumer Specialties', '其他消费特产', '其他消费特产', 5, 1, 'system', 0),
('stock_industry', '股票行业', 'Packaged Software', '软件产品', '软件产品', 6, 1, 'system', 0),
('stock_industry', '股票行业', 'Precious Metals', '贵金属', '贵金属', 7, 1, 'system', 0),
('stock_industry', '股票行业', 'Pharmaceuticals: Major', '制药:大型', '大型制药', 8, 1, 'system', 0),
('stock_industry', '股票行业', 'Engineering & Construction', '工程与建筑', '工程与建筑', 9, 1, 'system', 0),
('stock_industry', '股票行业', 'Miscellaneous Commercial Services', '其他商业服务', '其他商业服务', 10, 1, 'system', 0),
('stock_industry', '股票行业', 'Biotechnology', '生物技术', '生物技术', 11, 1, 'system', 0),
('stock_industry', '股票行业', 'Telecommunications Equipment', '通信设备', '通信设备', 12, 1, 'system', 0),
('stock_industry', '股票行业', 'Trucks/Construction/Farm Machinery', '卡车/工程/农业机械', '卡车/工程/农业机械', 13, 1, 'system', 0),
('stock_industry', '股票行业', 'Computer Communications', '计算机通信', '计算机通信', 14, 1, 'system', 0),
('stock_industry', '股票行业', 'Food: Major Diversified', '食品:大型多元化', '大型多元化食品', 15, 1, 'system', 0),
('stock_industry', '股票行业', 'Medical/Nursing Services', '医疗/护理服务', '医疗/护理服务', 16, 1, 'system', 0),
('stock_industry', '股票行业', 'Major Banks', '大型银行', '大型银行', 17, 1, 'system', 0),
('stock_industry', '股票行业', 'Internet Retail', '互联网零售', '互联网零售', 18, 1, 'system', 0),
('stock_industry', '股票行业', 'Specialty Telecommunications', '专业电信', '专业电信', 19, 1, 'system', 0),
('stock_industry', '股票行业', 'Integrated Oil', '综合石油', '综合石油', 20, 1, 'system', 0),
('stock_industry', '股票行业', 'Multi-Line Insurance', '多险种保险', '多险种保险', 21, 1, 'system', 0),
('stock_industry', '股'Apparel/Footwear Retail', '服装/鞋类零售', '服装/鞋类零售', 22, 1, 'system', 0),
('stock_industry', '股票行业', 'Electrical Products', '电气产品', '电气产品', 23, 1, 'system', 0),
('stock_industry', '股票行业', 'Coal', '煤炭', '煤炭', 24, 1, 'system', 0),
('stock_industry', '股票行业', 'Regional Banks', '区域银行', '区域银行', 25, 1, 'system', 0),
('stock_industry', '股票行业', 'Wireless Telecommunications', '无线通信', '无线通信', 26, 1, 'system', 0),
('stock_industry', '股票行业', 'Beverages: Non-Alcoholic', '饮料:非酒精', '非酒精饮料', 27, 1, 'system', 0),
('stock_industry', '股票行业', 'Investment Banks/Brokers', '投资银行/经纪商', '投资银行/经纪商', 28, 1, 'system', 0),
('stock_industry', '股票行业', 'Other Consumer Services', '其他消费服务', '其他消费服务', 29, 1, 'system', 0),
('stock_industry', '股票行业', 'Property/Casualty Insurance', '财产/意外保险', '财产/意外保险', 30, 1, 'system', 0),
('stock_industry', '股票行业', 'Finance/Rental/Leasing', '金融/租赁', '金融/租赁', 31, 1, 'system', 0),
('stock_industry', '股票行业', 'Electronics/Appliances', '电子/电器', '电子/电器', 32, 1, 'system', 0),
('stock_industry', '股票行业', 'Internet Software/Services', '互联网软件/服务', '互联网软件/服务', 33, 1, 'system', 0),
('stock_industry', '股票行业', 'Real Estate Development', '房地产开发', '房地产开发', 34, 1, 'system', 0),
('stock_industry', '股票行业', 'Apparel/Footwear', '服装/鞋类', '服装/鞋类', 35, 1, 'system', 0),
('stock_industry', '股票行业', 'Semiconductors', '半导体', '半导体', 36, 1, 'system', 0),
('stock_industry', '股票行业', 'Tools & Hardware', '工具与五金', '工具与五金', 37, 1, 'system', 0),
('stock_industry', '股票行业', 'Major Telecommunications', '大型电信', '大型电信', 38, 1, 'system', 0),
('stock_industry', '股票行业', 'Marine Shipping', '海运', '海运', 39, 1, 'system', 0),
('stock_industry', '股票行业', 'Other Transportation', '其他运输', '其他运输', 40, 1, 'system', 0),
('stock_industry', '股票行业', 'Electric Utilities', '电力公用事业', '电力公用事业', 41, 1, 'system', 0),
('stock_industry', '股票行业', 'Casinos/Gaming', '赌场/博彩', '赌场/博彩', 42, 1, 'system', 0),
('stock_industry', '股票行业', 'Specialty Stores', '专卖店', '专卖店', 43, 1, 'system', 0),
('stock_industry', '股票行业', 'Home Furnishings', '家居用品', '家居用品', 44, 1, 'system', 0),
('stock_industry', '股票行业', 'Consumer Sundries', '消费杂货', '消费杂货', 45, 1, 'system', 0),
('stock_industry', '股票行业', 'Restaurants', '餐饮', '餐饮', 46, 1, 'system', 0),
('stock_industry', '股票行业', 'Investment Managers', '投资管理', '投资管理', 47, 1, 'system', 0),
('stock_industry', '股票行业', 'Wholesale Distributors', '批发分销商', '批发分销商', 48, 1, 'system', 0),
('stock_industry', '股票行业', 'Movies/Entertainment', '电影/娱乐', '电影/娱乐', 49, 1, 'system', 0),
('stock_industry', '股票行业', 'Air Freight/Couriers', '航空货运/快递', '航空货运/快递', 50, 1, 'system', 0),
('stocndustry', '股票行业', 'Computer Processing Hardware', '计算机处理硬件', '计算机处理硬件', 51, 1, 'system', 0),
('stock_industry', '股票行业', 'Gas Distributors', '燃气分销商', '燃气分销商', 52, 1, 'system', 0),
('stock_industry', '股票行业', 'Construction Materials', '建筑材料', '建筑材料', 53, 1, 'system', 0),
('stock_industry', '股票行业', 'Aluminum', '铝', '铝', 54, 1, 'system', 0),
('stock_industry', '股票行业', 'Discount Stores', '折扣店', '折扣店', 55, 1, 'system', 0),
('stock_industry', '股票行业', 'Beverages: Alcoholic', '饮料:酒精', '酒精饮料', 56, 1, 'system', 0),
('stock_industry', '股票行业', 'Airlines', '航空公司', '航空公司', 57, 1, 'system', 0),
('stock_industry', '股票行业', 'Food: Meat/Fish/Dairy', '食品:肉/鱼/乳制品', '肉/鱼/乳制品', 58, 1, 'system', 0),
('stock_industry', '股票行业', 'Electronic Production Equipment', '电子生产设备', '电子生产设备', 59, 1, 'system', 0),
('stock_industry', '股票行业', 'Hotels/Resorts/Cruise lines', '酒店/度假村/邮轮', '酒店/度假村/邮轮', 60, 1, 'system', 0),
('stock_industry', '股票行业', 'Tobacco', '烟草', '烟草', 61, 1, 'system', 0),
('stock_industry', '股票行业', 'Electronic Components', '电子元件', '电子元件', 62, 1, 'system', 0),
('stock_industry', '股票行业', 'Information Technology Services', '信息技术服务', '信息技术服务', 63, 1, 'system', 0),
('stock_industry', '股票行业', 'Alternative Power Generation', '替代能源发电', '替代能源发电', 64, 1, 'system', 0),
('stock_industry', '股票行业', 'Household/Personal Care', '家庭/个人护理', '家庭/个人护理', 65, 1, 'system', 0),
('stock_industry', '股票行业', 'Chemicals: Specialty', '化工:特种', '特种化工', 66, 1, 'system', 0),
('stock_industry', '股票行业', 'Industrial Machinery', '工业机械', '工业机械', 67, 1, 'system', 0),
('stock_industry', '股票行业', 'Commercial Printing/Forms', '商业印刷/表格', '商业印刷/表格', 68, 1, 'system', 0),
('stock_industry', '股票行业', 'Other Metals/Minerals', '其他金属/矿产', '其他金属/矿产', 69, 1, 'system', 0),
('stock_industry', '股票行业', 'Industrial Specialties', '工业特种产品', '工业特种产品', 70, 1, 'system', 0),
('stock_industry', '股票行业', 'Electronic Equipment/Instruments', '电子设备/仪器', '电子设备/仪器', 71, 1, 'system', 0),
('stock_industry', '股票行业', 'Contract Drilling', '合同钻探', '合同钻探', 72, 1, 'system', 0),
('stock_industry', '股票行业', 'Water Utilities', '水务公用事业', '水务公用事业', 73, 1, 'system', 0),
('stock_industry', '股票行业', 'Aerospace & Defense', '航空航天与国防', '航空航天与国防', 74, 1, 'system', 0),
('stock_industry', '股票行业', 'Containers/Packaging', '容器/包装', '容器/包装', 75, 1, 'system', 0),
('stock_industry', '股票行业', 'Data Processing Services', '数据处理服务', '数据处理服务', 76, 1, 'system', 0),
('stock_industry', '股票行业', 'Publishing: Books/Magazines', '出版:书籍/杂志', '书籍/杂志出版', 77, 1, 'system', 0),
('stock_industry', '股票行业', 'Miscellaneous', '其他', '其他', 78, 1, 'system', 0),
('stock_industry', '股票行业', 'Medical Specialties', '医疗专科', '医疗专科', 79, 1, 'system', 0),
('stock_industry', '股票行业', 'Financial Conglomerates', '金融集团', '金融集团', 80, 1, 'system', 0),
('stock_industry', '股票行业', 'Food: Specialty/Candy', '食品:特产/糖果', '特产/糖果食品', 81, 1, 'system', 0),
('stock_industry', '股票行业', 'Railroads', '铁路', '铁路', 82, 1, 'system', 0),
('stock_industry', '股票行业', 'Recreational Products', '休闲产品', '休闲产品', 83, 1, 'system', 0),
('stock_industry', '股票行业', 'Steel', '钢铁', '钢铁', 84, 1, 'system', 0),
('stock_industry', '股票行业', 'Metal Fabrication', '金属加工', '金属加工', 85, 1, 'system', 0),
('stock_industry', '股票行业', 'Oil Refining/Marketing', '石油炼制/销售', '石油炼制/销售', 86, 1, 'system', 0),
('stock_industry', '股票行业', 'Personnel Services', '人力资源服务', '人力资源服务', 87, 1, 'system', 0),
('stock_industry', '股票行业', 'Oilfield Services/Equipment', '油田服务/设备', '油田服务/设备', 88, 1, 'system', 0),
('stock_industry', '股票行业', 'Miscellaneous Manufacturing', '其他制造业', '其他制造业', 89, 1, 'system', 0),
('stock_industry', '股票行业', 'Oil & Gas Pipelines', '油气管道', '油气管道', 90, 1, 'system', 0),
('stock_industry', '股票行业', 'Pulp & Paper', '纸浆与造纸', '纸浆与造纸', 91, 1, 'system', 0),
('stocustry', '股票行业', 'Textiles', '纺织', '纺织', 92, 1, 'system', 0),
('stock_industry', '股票行业', 'Chemicals: Agricultural', '化工:农业', '农业化工', 93, 1, 'system', 0),
('stock_industry', '股票行业', 'Pharmaceuticals: Other', '制药:其他', '其他制药', 94, 1, 'system', 0),
('stock_industry', '股票行业', 'Computer Peripherals', '计算机外设', '计算机外设', 95, 1, 'system', 0),
('stock_industry', '股票行业', 'Food Distributors', '食品分销商', '食品分销商', 96, 1, 'system', 0),
('stock_industry', '股票行业', 'Agricultural Commodities/Milling', '农产品/碾磨', '农产品/碾磨', 97, 1, 'system', 0),
('stock_industry', '股票行业', 'Electronics Distributors', '电子分销商', '电子分销商', 98, 1, 'system', 0),
('stock_industry', '股票行业', 'Hospital/Nursing Management', '医院/护理管理', '医院/护理管理', 99, 1, 'system', 0),
('stock_industry', '股票行业', 'Automotive Aftermarket', '汽车后市场', '汽车后市场', 100, 1, 'system', 0),
('stock_industry', '股票行业', 'Drugstore Chains', '连锁药店', '连锁药店', 101, 1, 'system', 0),
('stock_industry', '股票行业', 'Environmental Services', '环保服务', '环保服务', 102, 1, 'system', 0),
('stock_industry', '股票行业', 'Electronics/Appliance Stores', '电子/电器商店', '电子/电器商店', 103, 1, 'system', 0),
('stock_industry', '股票行业', 'Life/Health Insurance', '人寿/健康保险', '人寿/健康保险', 104, 1, 'system', 0),
('stock_industry', '股票行业tment Stores', '百货商店', '百货商店', 105, 1, 'system', 0),
('stock_industry', '股票行业', 'Chemicals: Major Diversified', '化工:大型多元化', '大型多元化化工', 106, 1, 'system', 0),
('stock_industry', '股票行业', 'Food Retail', '食品零售', '食品零售', 107, 1, 'system', 0),
('stock_industry', '股票行业', 'Publishing: Newspapers', '出版:报纸', '报纸出版', 108, 1, 'system', 0),
('stock_industry', '股票行业', 'Investment Trusts/Mutual Funds', '投资信托/共同基金', '投资信托/共同基金', 109, 1, 'system', 0),
('stock_industry', '股票行业', 'Oil & Gas Production', '油气生产', '油气生产', 110, 1, 'system', 0),
('stock_industry', '股票行业', 'Industrial Conglomerates', '工业集团', '工业集团', 111, 1, 'system', 0),
('stock_industry', '股票行业', 'Real Estate Investment Trusts',投资信托', '房地产投资信托', 112, 1, 'system', 0),
('stock_industry', '股票行业', 'Pharmaceuticals: Generic', '制药:仿制药', '仿制药', 113, 1, 'system', 0),
('stock_industry', '股票行业', 'Broadcasting', '广播', '广播', 114, 1, 'system', 0),
('stock_industry', '股票行业', 'Forest Products', '林产品', '林产品', 115, 1, 'system', 0),
('stock_industry', '股票行业', 'Insurance Brokers/Services', '保险经纪/服务', '保险经纪/服务', 116, 1, 'system', 0),
('stock_industry', '股票行业', 'Homebuilding', '住宅建筑', '住宅建筑', 117, 1, 'system', 0),
('stock_industry', '股票行业', 'Services to the Health Industry', '医疗行业服务', '医疗行业服务', 118, 1, 'system', 0),
('stock_industry', '股票行业', 'Trucking', '货运', '货运', 119, 1, 'system', 0),
('stock_industry', '股票行业', 'Building Products', '建筑产品', '建筑产品', 120, 1, 'system', 0),
('stock_industry', '股票行业', 'Catalog/Specialty Distribution', '目录/专业分销', '目录/专业分销', 121, 1, 'system', 0),
('stock_industry', '股票行业', 'Office Equipment/Supplies', '办公设备/用品', '办公设备/用品', 122, 1, 'system', 0),
('stock_industry', '股票行业', 'Media Conglomerates', '媒体集团', '媒体集团', 123, 1, 'system', 0),
('stock_industry', '股票行业', 'Cable/Satellite TV', '有线/卫星电视', '有线/卫星电视', 124, 1, 'system', 0),
('stock_industry', '股票行业', 'Savings Banks', '储蓄银行', '储蓄银行', 125, 1, 'system', 0);
